add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[ ](bold cyan)"

[username]
style_user = "bold green"
show_always = true 

[git_commit]
commit_hash_length = 8
style = "bold white"

# this is only relevant for laptops
[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
